[dependencies]
"php/php" = "=8.3.4" # Wersja PHP obsługująca rozszerzenia i sesje w Wasmer

[fs]
"/app" = "." 

[[command]]
name = "run"
module = "php/php:php"
runner = "wasi"

[command.annotations.wasi]
main-args = [
    "-r", "if(!file_exists('/app/database')) mkdir('/app/database', 0777, true); if(!file_exists('/app/database/database.sqlite')) touch('/app/database/database.sqlite');",
    "-t", "/app/public", 
    "-S", "localhost:8080"
]