name = "kaliuzhnyi-nazariy
/barber"
version = "0.1.0"
description = ""

"php/php" = "=8.3.4" 

"/app" = "."

name = "run"
module = "php/php:php"
runner = "wasi"

main-args = [
    "-t", "/app/public", 
    "-S", "0.0.0.0:8080"
]

APP_ENV = "production"
APP_KEY = "base64:NEGpCMovMjaI1KQE4Ct+vfQjBSM4Z9DakZWUaAskYEs=;
DB_CONNECTION = "pgsql"
DB_HOST = "db.ebdvmhbdxchbkkmgtpnn.supabase.co" 
DB_PORT = "5432"
DB_DATABASE = "postgres"
DB_USERNAME = "postgres"
DB_SSLMODE = "require"

SESSION_DRIVER = "cookie"
CACHE_STORE = "array"
LOG_CHANNEL = "stderr" 
